CREATE TABLE [dbo].[Task]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [TaskName] NVARCHAR(100) NOT NULL, 
    [SetDate] NVARCHAR(50) NOT NULL, 
    [ExpirationDate] NVARCHAR(50) NULL, 
    [Status] NVARCHAR(50) NOT NULL
)
